### ISSUE TITLE
Embed Swagger UI in Sphinx pages

### ISSUE THREAD

**Issue by DanielWhite95** [SAP/swagger-plugin-for-sphinx#53]
Hi, 
I like the approach of this plugin to automate the build of swagger and sphinx pages, but I think that it will be better if Swagger UIs can be embedded into final Sphinx pages, instead of standalone pages.

I would like to help to implement this feature, I also created a fork that implement a new Sphinx directive that can be used to embed the UI in any Sphinx page

**Comment by DanielWhite95** [comment]
If someone wants to check, the implementation of my fork is here: https://github.com/DanielWhite95/swagger-plugin-for-sphinx

**Comment by kasium** [comment]
Thanks a lot for the idea and the fork. Let me have a look in the next days. In the case you hear nothing from me, feel free to leave a "ping" comment anytime

**Comment by kasium** [comment]
@DanielWhite95 so, I just took some time to look through your code. First, let me emphasize that I like the idea a lot! However, the code looks quite hacky to be honest. I'm not sure if this is just the way how sphinx directives look but just the code needed for the jinja file and all the additional libraries are enormous. Did you check if there is any way to make it less "hacky"?

**Comment by kasium** [comment]
Have you tried using iframes? Assuming that the swagger html was built and put into the `_static` folder, you can create a rst page with the content

```rst
.. raw:: html
   :file: ../_static/openapi.html
```

This seems to be easier that a full custom HTML. Ignoring how the HTML ends up there, is that a way you would like?

**Comment by kasium** [comment]
Which problem do you seen then? What doesn't work?

**Comment by DanielWhite95** [comment]
In the output html produced, all <script> tags in the template were removed

**Comment by kasium** [comment]
Okay, here is what I do with pyhon3.11, latest sphinx version and latest furo version

Config
```py
swagger = [
    {
        "name": "OpenAPI Specification",
        "page": "rest_api/openapi",
        "options": {"url": "../_static/openapi.yaml"},
    }
]
```

1. ,Build the documentation as usual
2. Move _build/rest_api/openapi.html to _static
3. Create a new page with the following content and add it the doctree
```rst
Test
====

.. raw:: html
   :file: ../_static/openapi.html
```
4. Build the documentation again

I don't know what you see, but when I check the HTML of the new generated page I see something like starting at line 220

```html
<h1>Test<a class="headerlink" href="#test" title="Permalink to this heading">#</a></h1>
<!DOCTYPE html>
<html>
    <head>
        <title>OpenAPI Specification</title>
        <link href="https://cdn.jsdelivr.net/npm/swagger-ui-dist@latest/swagger-ui.css" rel="stylesheet" type="text/css"/>
        <meta charset="utf-8"/>
    </head>
    <body>
        <div id="swagger-ui-container"></div>
        <script src="https://cdn.jsdelivr.net/npm/swagger-ui-dist@latest/swagger-ui-standalone-preset.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/swagger-ui-dist@latest/swagger-ui-bundle.js"></script>
        <script>
            config = {'url': '../_static/openapi.yaml'}
            config["dom_id"] = "#swagger-ui-container"
            window.onload = function() {
                window.ui = SwaggerUIBundle(config);
            }
        </script>
```
And the page works as expected. Can you please send me details steps to reproduce your issue. If the scenario works, I would just propose to add an embedded feature instead of your idea.

**Comment by DanielWhite95** [comment]
I tried again following your steps and with latest versions it works correctly (probably it was a problem with older versions of sphinx). 
But this workflow seems a bit tricky to me. For users, it's more natural to have a `swagger-ui` sphinx directive to which you can pass only your specification.
I would like to avoid to build two times the docs because I have to re-import manually the page produced in the first build

**Comment by kasium** [comment]
I agree. The goal would be to have an own directive which just uses `raw` behind the scenes

**Comment by DanielWhite95** [comment]
Sorry, but I don't get what is the problem with my implementation. I think it's best to append the html code with the visitHTML hook, because for other formats the SwaggerUI will have no sense.
`raw` can be easier to implement, but for other formats can break the output

**Comment by kasium** [comment]
You are right, but as said, you add a a lot of custom HTML which might change over time and which needs to be maintained. Also a hell of addition JS files are needed. Just by looking at the complexity I would go for the easy solution for now
